apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job-application-tracker
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sathyamoorthy-s/Job-application-tracker.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: job-tracker

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true