apiVersion: v1
kind: Service
metadata:
  name: job-application-tracker
  namespace: job-tracker
spec:
  selector:
    app: job-application-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
